name: Trigger auto deployment for musicstore

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/musicstore-AutoDeployTrigger-6890cc15-ea76-4984-bb0b-b73b7457aca0.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MUSICSTORE_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/src
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: ca28e1ae246facr.azurecr.io
          registryUsername: ${{ secrets.MUSICSTORE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MUSICSTORE_REGISTRY_PASSWORD }}
          containerAppName: musicstore
          resourceGroup: rg-aullah-aca
          imageToBuild: ca28e1ae246facr.azurecr.io/musicstore:${{ github.sha }}
          
            

     

